# Generated by Django 4.0.3 on 2022-04-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, through='blogger.CategoryToPost', to='blogger.category'),
        ),
    ]
