# Generated by Django 4.0.3 on 2022-04-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0002_alter_post_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
