# Generated by Django 4.0.3 on 2022-04-28 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0003_post_post_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('image_url', models.URLField()),
                ('action_form', models.TextField(blank=True)),
            ],
        ),
    ]
